import { createCoinHologramMaterial } from './coinHologramMaterial.js';

/**
 * Built-in renderer material definitions (no external 3D library).
 * Colours tuned for the built-in Canvas rasteriser (`WorldRenderer`).
 *
 * @returns {Record<string, object>}
 */
export function createMaterialPalette() {
  return {
    static: {
      kind: 'standard',
      baseColor: hexToRgb(0x8e40b0),
      roughness: 0.88,
      metalness: 0.03,
      emissive: hexToRgb(0x5c2480),
      emissiveIntensity: 0.34,
      opacity: 1,
      transparent: false,
      depthWrite: true,
      wireframe: false,
      polygonOffset: true,
      polygonOffsetFactor: 1,
      polygonOffsetUnits: 1,
      roughnessMap: null,
    },
    plaza: {
      kind: 'standard',
      baseColor: hexToRgb(0x8e40b0),
      roughness: 0.86,
      metalness: 0.04,
      emissive: hexToRgb(0x682898),
      emissiveIntensity: 0.38,
      opacity: 1,
      transparent: false,
      depthWrite: true,
      wireframe: false,
      polygonOffset: true,
      polygonOffsetFactor: 3,
      polygonOffsetUnits: 1,
      roughnessMap: null,
    },
    path: {
      kind: 'standard',
      baseColor: hexToRgb(0x8e40b0),
      roughness: 0.88,
      metalness: 0.04,
      emissive: hexToRgb(0x562070),
      emissiveIntensity: 0.32,
      opacity: 1,
      transparent: false,
      depthWrite: true,
      wireframe: false,
      polygonOffset: true,
      polygonOffsetFactor: 1,
      polygonOffsetUnits: 1,
      roughnessMap: null,
    },
    pathWide: {
      kind: 'standard',
      baseColor: hexToRgb(0xf860f0),
      roughness: 0.76,
      metalness: 0.06,
      emissive: hexToRgb(0xe028d0),
      emissiveIntensity: 0.58,
      opacity: 1,
      transparent: false,
      depthWrite: true,
      wireframe: false,
      polygonOffset: true,
      polygonOffsetFactor: 2,
      polygonOffsetUnits: 1,
      roughnessMap: null,
    },
    ramp: {
      kind: 'standard',
      baseColor: hexToRgb(0xf860f0),
      roughness: 0.78,
      metalness: 0.05,
      emissive: hexToRgb(0xd020b8),
      emissiveIntensity: 0.52,
      opacity: 1,
      transparent: false,
      depthWrite: true,
      wireframe: false,
      polygonOffset: true,
      polygonOffsetFactor: 2,
      polygonOffsetUnits: 1,
      roughnessMap: null,
    },
    goal: {
      kind: 'standard',
      baseColor: hexToRgb(0xff6b35),
      roughness: 0.35,
      metalness: 0.15,
      emissive: hexToRgb(0x8b2500),
      emissiveIntensity: 0.5,
      opacity: 0.45,
      transparent: true,
      depthWrite: false,
      wireframe: false,
      polygonOffset: false,
      roughnessMap: null,
    },
    zoneStart: {
      kind: 'standard',
      baseColor: hexToRgb(0x0abdc6),
      roughness: 0.38,
      metalness: 0.22,
      emissive: hexToRgb(0x045a61),
      emissiveIntensity: 0.45,
      opacity: 0.42,
      transparent: true,
      depthWrite: false,
      wireframe: false,
      polygonOffset: false,
      roughnessMap: null,
    },
    zoneEnd: {
      kind: 'standard',
      baseColor: hexToRgb(0xff6b35),
      roughness: 0.34,
      metalness: 0.2,
      emissive: hexToRgb(0x8b2500),
      emissiveIntensity: 0.5,
      opacity: 0.42,
      transparent: true,
      depthWrite: false,
      wireframe: false,
      polygonOffset: false,
      roughnessMap: null,
    },
    lattice: {
      kind: 'standard',
      baseColor: hexToRgb(0x1cd4e0),
      roughness: 0.84,
      metalness: 0.1,
      emissive: hexToRgb(0x0898a2),
      emissiveIntensity: 0.4,
      opacity: 1,
      transparent: false,
      depthWrite: true,
      wireframe: true,
      polygonOffset: true,
      polygonOffsetFactor: 1,
      polygonOffsetUnits: 1,
      roughnessMap: null,
    },
    coin: createCoinHologramMaterial(),
    marble: {
      kind: 'standard',
      baseColor: hexToRgb(0xfff59a),
      roughness: 0.14,
      metalness: 0.42,
      emissive: hexToRgb(0xffee00),
      emissiveIntensity: 1.1,
      opacity: 1,
      transparent: false,
      depthWrite: true,
      wireframe: false,
      polygonOffset: false,
      roughnessMap: null,
    },
  };
}

/** @param {number} hex */
function hexToRgb(hex) {
  return [((hex >> 16) & 255) / 255, ((hex >> 8) & 255) / 255, (hex & 255) / 255];
}
